openapi: 3.0.3
info:
  title: Solat API Malaysia
  x-logo:
    url: https://fajarhac.com/static/7035a9f0c12ca862b0565dd65b0443a7/67a33/site-logo.png
    altText: Solat API Malaysia logo
  description: |
    Solat API Malaysia, mengambil data waktu solat untuk lokasi-lokasi di Malaysia melalui laman web JAKIM.

    Data yang diambil dari laman web JAKIM akan dimasukkan di dalam databes kami sendiri, untuk tujuan kestabilan API.

    API ini dilepaskan kepada umum secara percuma, **tanpa sebarang janji dan waranti**. Tuan puan boleh menggunakan API ini sebagaimana disediakan.

    ## Kualiti dan kesahihan data

    Tarikh terakhir data dikaut dari laman web JAKIM (e-solat) ialah **14hb Januari 2024**.

    Walaubagaimanapun, untuk menjamin kesahihan data, Solat API Malaysia pada setiap hari akan menyemak waktu solat untuk 10 zon secara rawak. Kemudian membandingkan data tersebut dengan data dalam Solat API Malaysia.

    Sekiranya, ada perbezaan, satu isu baru akan dibuat di github.
  version: 1.0.0
  contact:
    name: Fakhrullah Padzil (Github)
    url: https://github.com/fakhrullah/solatapi
    x-twitter: https://twitter.com/fajarhac
servers:
  - url: https://solatapi.fajarhac.com
  - url: http://localhost:4000
components:
  schemas:
    zone:
      type: string
      enum:
        - jhr01
        - jhr02
        - jhr03
        - jhr04
        - kdh01
        - kdh02
        - kdh03
        - kdh04
        - kdh05
        - kdh06
        - kdh07
        - ktn01
        - ktn03
        - mlk01
        - ngs01
        - ngs02
        - phg01
        - phg02
        - phg03
        - phg04
        - phg05
        - phg06
        - prk01
        - prk02
        - prk03
        - prk04
        - prk05
        - prk06
        - prk07
        - pls01
        - png01
        - sbh01
        - sbh02
        - sbh03
        - sbh04
        - sbh05
        - sbh06
        - sbh07
        - sbh08
        - sbh09
        - swk01
        - swk02
        - swk03
        - swk04
        - swk05
        - swk06
        - swk07
        - swk08
        - swk09
        - sgr01
        - sgr02
        - sgr03
        - trg01
        - trg02
        - trg03
        - trg04
        - wly01
        - wly02
      example: trg02
    state:
      type: string
      enum:
        - johor
        - kedah
        - kelantan
        - melaka
        - negeri sembilan
        - pahang
        - perak
        - perlis
        - pulau pinang
        - sabah
        - sarawak
        - selangor
        - terengganu
        - putrajaya
        - kuala lumpur
        - labuan
      example: terengganu
    location:
      type: string
      enum:
        - pulau aur
        - pemanggil
        - kota tinggi
        - mersing
        - johor bahru
        - kluang
        - pontian
        - batu pahat
        - muar
        - segamat
        - gemas
        - kota setar
        - kubang pasu
        - pokok sena
        - pendang
        - kuala muda
        - yan
        - padang terap
        - sik
        - baling
        - kulim
        - bandar bahru
        - langkawi
        - gunung jerai
        - kota bahru
        - bachok
        - pasir puteh
        - tumpat
        - pasir mas
        - tanah merah
        - machang
        - kuala krai
        - mukim chiku
        - jeli
        - gua musang
        - mukim galas
        - bertam
        - bandar melaka
        - alor gajah
        - jasin
        - masjid tanah
        - merlimau
        - nyalas
        - jempol
        - tampin
        - port dickson
        - seremban
        - kuala pilah
        - jelebu
        - rembau
        - pulau tioman
        - kuantan
        - pekan
        - rompin
        - muadzam shah
        - maran
        - chenor
        - temerloh
        - bera
        - jerantut
        - jengka
        - bentong
        - raub
        - kuala lipis
        - genting sempah
        - janda baik
        - bukit tinggi
        - bukit fraser
        - genting highlands
        - cameron highlands
        - tapah
        - slim river
        - tanjung malim
        - ipoh
        - batu gajah
        - kampar
        - sungai siput
        - kuala kangsar
        - pengkalan hulu
        - grik
        - lenggong
        - temengor
        - belum
        - teluk intan
        - bagan datuk
        - kampung gajah
        - seri iskandar
        - beruas
        - parit
        - lumut
        - sitiawan
        - pulau pangkor
        - selama
        - taiping
        - bagan serai
        - parit buntar
        - bukit larut
        - kangar
        - padang besar
        - arau
        - pulau pinang
        - sandakan timur
        - bukit garam
        - semawang
        - temanggong
        - tambisan
        - sukau
        - pinangah
        - terusan
        - beluran
        - kuamut
        - telupid
        - sandakan barat
        - lahad datu
        - kunak
        - silabukan
        - tungku
        - sahabat
        - semporna
        - tawau timur
        - bandar tawau
        - balong
        - merotai
        - kalabakan
        - tawau barat
        - kudat
        - kota marudu
        - pitas
        - pulau banggi
        - gunung kinabalu
        - papar
        - ranau
        - kota belud
        - tuaran
        - penampang
        - kota kinabalu
        - putatan
        - pantai barat
        - pensiangan
        - keningau
        - tambunan
        - nabawan
        - sipitang
        - membakut
        - beaufort
        - kuala penyu
        - weston
        - tenom
        - long pa sia
        - limbang
        - sundar
        - terusan
        - lawas
        - niah
        - belaga
        - sibuti
        - miri
        - bekenu
        - marudi
        - song
        - balingian
        - sebauh
        - bintulu
        - tatau
        - kapit
        - igan
        - kanowit
        - sibu
        - dalat
        - oya
        - belawai
        - matu
        - daro
        - sarikei
        - julau
        - bitangor
        - rajang
        - kabong
        - lingga
        - sri aman
        - engkelili
        - betong
        - spaoh
        - pusa
        - saratok
        - roban
        - debak
        - samarahan
        - simunjan
        - serian
        - sebuyau
        - meludam
        - kuching
        - bau
        - lundu
        - sematan
        - zon khas
        - gombak
        - hulu selangor
        - rawang
        - hulu langat
        - sepang
        - petaling
        - shah alam
        - sabak bernam
        - kuala selangor
        - klang
        - kuala langat
        - kuala terengganu
        - marang
        - kuala nerus
        - besut
        - setiu
        - hulu terengganu
        - kemaman
        - dungun
        - putrajaya
        - kuala lumpur
        - labuan
      example: setiu
    zone_detail:
      type: object
      properties:
        zone:
          $ref: "#/components/schemas/zone"
        state:
          $ref: "#/components/schemas/state"
        locations:
          type: array
          items:
            $ref: "#/components/schemas/location"
          example:
            - setiu
            - besut
    zones:
      type: array
      description: List of zones
      items:
        $ref: "#/components/schemas/zone_detail"
      example:
        - zone: jhr01
          state: johor
          locations:
            - pulau aur
            - pemanggil
        - zone: wly02
          state: labuan
          locations:
            - labuan
    prayer_time:
      type: object
      description: Daily prayer time
      properties:
        date:
          type: string
          example: 04-11-2021
        date_timestamp:
          type: number
          example: 1635955200000
        imsak:
          anyOf:
            - type: number
              example: 1635955200000
            - type: string
              example:
                - 5:30 am
                - "05:30:00"
        subuh:
          anyOf:
            - type: number
              example: 1635955200000
            - type: string
              example:
                - 5:30 am
                - "05:30:00"
        syuruk:
          anyOf:
            - type: number
              example: 1635955200000
            - type: string
              example:
                - 5:30 am
                - "05:30:00"
        zohor:
          anyOf:
            - type: number
              example: 1635955200000
            - type: string
              example:
                - 5:30 am
                - "05:30:00"
        asar:
          anyOf:
            - type: number
              example: 1635955200000
            - type: string
              example:
                - 5:30 am
                - "05:30:00"
        maghrib:
          anyOf:
            - type: number
              example: 1635955200000
            - type: string
              example:
                - 5:30 am
                - "05:30:00"
        isyak:
          anyOf:
            - type: number
              example: 1635955200000
            - type: string
              example:
                - 5:30 am
                - "05:30:00"
    prayer_times:
      type: array
      description: List of daily prayer times
      items:
        $ref: "#/components/schemas/prayer_time"
tags:
  - name: times
    description: Waktu solat
  - name: zones
    description: Zon, Negeri, Wilayah dan Lokasi
paths:
  /times:
    get:
      tags:
        - times
      description: Get Solat Time
      parameters:
        - name: zone
          description: |
            Zone code for solat zone. Refer: [Zones Docs](/zones)
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/zone"
        - name: from
          in: query
          required: true
          description: Date in format dd-MM-YYYY. For example 01112021 for 4th November 2021
          schema:
            type: string
            example: 04-11-2021
            description: Date in format dd-MM-YYYY. For example 04-11-2021 for 4th November 2021
        - name: to
          in: query
          required: false
          schema:
            type: string
            example: 06-11-2021
            description: Date in format dd-MM-YYYY. For example 06-11-2021 for 6th November 2021
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum:
              - 12-hour
              - 24-hour
              - timestamp
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  zone_detail:
                    $ref: "#/components/schemas/zone_detail"
                  prayer_times:
                    $ref: "#/components/schemas/prayer_times"
  "/today/{zone}":
    get:
      tags:
        - times
      description: Get Solat Time for today
      parameters:
        - name: zone
          description: |
            Zone code for solat zone. Refer: [Zones Docs](/zones)
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/zone"
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum:
              - 12-hour
              - 24-hour
              - timestamp
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  zone_detail:
                    $ref: "#/components/schemas/zone_detail"
                  prayer_times:
                    $ref: "#/components/schemas/prayer_times"
  "/tomorrow/{zone}":
    get:
      tags:
        - times
      description: Get Solat Time for for tomorrow
      parameters:
        - name: zone
          description: |
            Zone code for solat zone. Refer: [Zones Docs](/zones)
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/zone"
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum:
              - 12-hour
              - 24-hour
              - timestamp
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  zone_detail:
                    $ref: "#/components/schemas/zone_detail"
                  prayer_times:
                    $ref: "#/components/schemas/prayer_times"
  "/yesterday/{zone}":
    get:
      tags:
        - times
      description: Get Solat Time for for yesterday
      parameters:
        - name: zone
          description: |
            Zone code for solat zone. Refer: [Zones Docs](/zones)
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/zone"
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum:
              - 12-hour
              - 24-hour
              - timestamp
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  zone_detail:
                    $ref: "#/components/schemas/zone_detail"
                  prayer_times:
                    $ref: "#/components/schemas/prayer_times"
  /zones:
    get:
      tags:
        - zones
      description: List of zones
      responses:
        "200":
          description: |
            Show all list of zones.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/zones"
  "/zones/{zone}":
    get:
      tags:
        - zones
      description: Get detail of zone
      parameters:
        - name: zone
          required: true
          in: path
          description: The code of zone
          schema:
            $ref: "#/components/schemas/zone"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/zone_detail"
  /info:
    get:
      tags:
        - info
      description: About SolatAPI Malaysia
      responses:
        "200":
          description: OK
  /:
    get:
      tags:
        - info
      description: About SolatAPI Malaysia
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
  /health:
    get:
      tags:
        - info
      description: About SolatAPI Malaysia
      responses:
        "200":
          description: Site is running properly
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
