GET http://localhost:4000/v2/times?zone=sgr01&from=01-01-2023

###
GET http://localhost:4000/v2/times?zone=sgr01&from=01-01-2023&format=12-hour

###
GET http://localhost:4000/v2/times?zone=sgr01&from=04-11-2022&format=24-hour

###
GET http://localhost:4000/v2/times?zone=sgr01&from=01-01-2023&to=07-01-2023

###
GET http://localhost:4000/v2/times?zone=trg02&from=01-01-2023&to=07-01-2023&format=12-hour

###
# Should error because SolatAPI only contain data from 2022 ~ 2023

GET http://localhost:4000/v2/times?zone=trg02&from=01-01-2021&format=12-hour

###
GET http://localhost:4000/v2/today/sgr01

###
GET http://localhost:4000/v2/today/trg02?format=24-hour

###
GET http://localhost:4000/v2/tomorrow/sgr01

###
GET http://localhost:4000/v2/yesterday/sgr01

###
GET http://localhost:4000/v2/yesterday/kdh01?format=12-hour
